### ISSUE TITLE
Server Setup Feature

### ISSUE THREAD

**Issue by nprail** [mcpr/mcpr-cli#1]
Add the server setup feature. 

### Requirements
* Cross-Platform
* Multiple Server Types (Spigot, CraftBukkit, Vanilla)

### Tasks
- [x] Build/Download server jar

### Supported Server Types
- [x] [SpigotMC](https://www.spigotmc.org) (with [BuildTools](https://www.spigotmc.org/threads/buildtools-updates-information.42865/))
- [x] [CraftBukkit](https://bukkit.org/) (with [BuildTools](https://www.spigotmc.org/threads/buildtools-updates-information.42865/))
- [x] Vanilla (Simply Download)
