### ISSUE TITLE
Rename to MCPR CLI

### ISSUE THREAD

**Issue by nprail** [mcpr/mcpr-cli#7]
Rename this project to MCPR CLI!

### To-Do
- [x] Move Repo to mcpr/cli
- [x] Change Command to `mcpr`
- [x] Update [Scripts](https://github.com/HexagonMinecraft/mc-cli/tree/master/scripts)
- [x] Update [`control`](https://github.com/HexagonMinecraft/mc-cli/blob/master/control)
 - [x] Update [`README.md`](https://github.com/HexagonMinecraft/mc-cli/blob/master/README.md)
